
version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run:
          name: "Install node"
          command: npm i
      - save_cache:
          paths:
            - /src/node_modules
          key: "npm"
      - run:
          name: "Lint"
          command: npm run lint

  test:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          keys:
            - "npm"
      - run:
          name: "test"
          command: npm run test

  analyze:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          keys:
            - "npm"
      - run:
          name: "audit"
          command: npm audit

workflows:
  say-hello-workflow:
    jobs:
      - build
      - test: 
          requires:
            - build
      - analyze:
          requires:
            - test
